/**
 * Generates one placeholder screen component per entry in
 * NAVIGATION_STRUCTURE, plus the lazy-loaded route table that wires them
 * all into React Router. Re-run any time navigationStructure.js changes:
 *
 *   node scripts/generate-screens.mjs
 *
 * Safe to re-run — it overwrites generated files deterministically.
 */
import { mkdirSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { NAVIGATION_STRUCTURE } from "../src/constants/navigationStructure.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SRC = path.join(__dirname, "..", "src");
const SCREENS_DIR = path.join(SRC, "screens");
const NAV_DIR = path.join(SRC, "navigation");

let screenCount = 0;
const importLines = [];
const routeEntries = [];

for (const module of NAVIGATION_STRUCTURE) {
  const moduleDir = path.join(SCREENS_DIR, module.key);
  mkdirSync(moduleDir, { recursive: true });

  for (const screen of module.screens) {
    const screenDir = path.join(moduleDir, screen.key);
    mkdirSync(screenDir, { recursive: true });

    const filePath = path.join(screenDir, `${screen.key}.jsx`);
    const fileContents = `import ScreenTemplate from "../../_shared/ScreenTemplate.jsx";

export default function ${screen.key}() {
  return (
    <ScreenTemplate
      module="${module.label}"
      moduleSlug="${module.slug}"
      screen="${screen.label}"
      icon="${module.icon}"
    />
  );
}
`;
    writeFileSync(filePath, fileContents);
    screenCount += 1;

    const importName = `${module.key}_${screen.key}`;
    const importPath = `../screens/${module.key}/${screen.key}/${screen.key}.jsx`;
    importLines.push(`const ${importName} = lazy(() => import("${importPath}"));`);
    routeEntries.push(
      `  { path: "/${module.slug}/${screen.slug}", Component: ${importName}, module: "${module.label}", screen: "${screen.label}" },`
    );
  }
}

mkdirSync(NAV_DIR, { recursive: true });

const routesFile = `/**
 * AUTO-GENERATED by scripts/generate-screens.mjs — do not hand-edit.
 * Re-run the generator after changing navigationStructure.js.
 */
import { lazy } from "react";

${importLines.join("\n")}

export const screenRoutes = [
${routeEntries.join("\n")}
];
`;

writeFileSync(path.join(NAV_DIR, "routes.generated.js"), routesFile);

console.log(`Generated ${screenCount} placeholder screens across ${NAVIGATION_STRUCTURE.length} modules.`);
console.log(`Wrote ${path.join(NAV_DIR, "routes.generated.js")}`);
